import Image from 'next/image';
import Link from 'next/link';
import type { ContentRecord, Locale } from '@/lib/types';
import { localized } from '@/lib/types';
import { getDictionary } from '@/lib/i18n';
import { ContentCard } from './content-card';

export function HomePage({locale,services,articles,pageRecord}:{locale:Locale;services:ContentRecord[];articles:ContentRecord[];pageRecord?:ContentRecord}) { const t=getDictionary(locale); const heroTitle=pageRecord?localized(pageRecord,'title',locale):locale==='id'?'Hidup penuh momen. Buat jadi berkesan.':'Life is an event. Make it live.'; const heroDescription=pageRecord?localized(pageRecord,'description',locale):locale==='id'?'Kami mengubah momen perusahaan menjadi cerita bersama yang benar-benar ingin dikenang.':'We turn company moments into shared stories people actually want to remember.'; return <main id="main">
  <section className="hero"><div className="hero-noise"/><div className="hero-copy"><p className="overline">Live event partner · Jakarta · Indonesia</p><h1><span>{heroTitle}</span></h1><div className="hero-actions"><p>{heroDescription}</p><Link className="pill-button" href={`/${locale}/services`}>{locale==='id'?'Lihat layanan kami':'See what we do'} <span>↗</span></Link></div></div>
  <figure className="hero-image"><video autoPlay muted loop playsInline poster="/assets/images/events/img-7331-poster.jpg"><source src="/assets/video/img-7331-hero-540.m4v" type="video/mp4"/></video><figcaption><span>{locale==='id'?'Tempat nyata.':'Real place.'}</span><span>{locale==='id'?'Energi bersama.':'Shared energy.'}</span><span>{locale==='id'?'Momen hidup.':'Moment alive.'}</span></figcaption></figure>
  <aside className="hero-ticket"><small>ADMIT EVERYONE</small><b>AIUEO / LIVE</b><p>{locale==='id'?'Satu ide. Ratusan bagian bergerak. Satu hari untuk manusia.':'One idea. A hundred moving parts. One day built around people.'}</p></aside></section>
  <div className="live-strip"><div>WE PLAN ✦ YOU SHOW UP ✦ EVERYONE CONNECTS ✦ THE MOMENT LIVES ✦</div></div>
  <section className="manifesto home"><p className="section-label">01 / {t.about}</p><h2>{locale==='id'?'Bukan sekadar event organizer.':'Not just an event organizer.'}</h2><div className="manifesto-media"><Image src="/assets/images/events/team-building.jpg" alt="AIUEO team building" fill sizes="(max-width: 700px) 100vw, 55vw"/></div><p>{locale==='id'?'Kami adalah pembuat momen, penggerak suasana, penjaga detail, dan pemelihara energi.':'We are moment makers, crowd movers, detail catchers, and energy keepers.'}</p></section>
  <section className="services-section"><div className="section-heading"><p>02 / {t.services}</p><h2>{locale==='id'?'Apa yang bisa kita hidupkan?':'What can we make live?'}</h2></div><div className="service-list">{services.map((service,index)=><Link key={service.id} href={`/${locale}/services/${localized(service,'slug',locale)}`}><span>{String(index+1).padStart(2,'0')}</span><h3>{localized(service,'title',locale)}</h3><p>{localized(service,'description',locale)}</p><b>↗</b></Link>)}</div></section>
  <section className="field-section"><div className="section-heading"><p>03 / {t.resources}</p><h2>{locale==='id'?'Segar dari lapangan.':'Fresh from the field.'}</h2></div><div className="content-grid">{articles.map(item=><ContentCard key={item.id} item={item} locale={locale} base="news"/>)}<article className="field-photo"><Image src="/assets/images/events/rafting.jpg" alt="AIUEO rafting activity" fill sizes="(max-width: 700px) 100vw, 50vw"/></article></div></section>
  <section className="collab-section"><h2>{t.contactTitle}</h2><div><p>{t.contactCopy}</p><Link className="pill-button ink" href={`/${locale}/contact`}>{t.contactCta}<span>↗</span></Link></div></section>
  </main> }
